import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  headerTitle: { fontFamily: "PlayfairDisplay_600SemiBold", fontSize: 22, color: "#3D2E22", letterSpacing: -0.3 },
  mascot: { width: 176, height: 176 },
  emptyTitle: { marginTop: 14, fontFamily: "PlayfairDisplay_600SemiBold", fontSize: 22, color: "#3D2E22" },
  emptySubtitle: { marginTop: 8, textAlign: "center", fontFamily: "Inter_400Regular", fontSize: 14, color: "#7A6A5A" },
  progressRow: { flexDirection: "row", gap: 10, marginTop: 18 },
  progressDot: { width: 10, height: 10, borderRadius: 5 },
  progressDotFilled: { backgroundColor: "#D4A574" },
  progressDotEmpty: { backgroundColor: "#E9DED1" },
  progressText: { marginTop: 10, fontFamily: "Inter_500Medium", fontSize: 13, color: "#9B8B7F" },
  primaryCta: {
    marginTop: 20,
    borderRadius: 999,
    paddingHorizontal: 18,
    paddingVertical: 11,
    backgroundColor: "#D4A574",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  primaryCtaText: { color: "#FFFFFF", fontFamily: "Inter_600SemiBold", fontSize: 14 },
  tipRow: {
    marginTop: 18,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: "#F4EADF",
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
  },
  tipText: { flex: 1, color: "#8F7D6B", fontFamily: "Inter_400Regular", fontSize: 12, lineHeight: 17 },
});
