import { StyleSheet } from "react-native";
import { colors } from "@/lib/theme";

export const s = StyleSheet.create({
  headerTitle: {
    fontFamily: "PlayfairDisplay_600SemiBold",
    fontSize: 24,
    color: colors.textPrimary,
    letterSpacing: -0.4,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 12,
    gap: 16,
  },
  heroCard: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.cardBg,
    paddingHorizontal: 16,
    paddingVertical: 16,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.06,
    shadowRadius: 14,
    elevation: 2,
  },
  heroTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  heroTopLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  sparkleBadge: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.primaryLight,
  },
  heroEyebrow: {
    fontFamily: "Inter_500Medium",
    fontSize: 12,
    color: colors.textSecondary,
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  heroTitle: {
    marginTop: 10,
    fontFamily: "PlayfairDisplay_600SemiBold",
    fontSize: 28,
    lineHeight: 32,
    color: colors.textPrimary,
    letterSpacing: -0.5,
  },
  heroDescription: {
    marginTop: 8,
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 19,
    color: colors.textMuted,
  },
  heroStatsRow: {
    marginTop: 14,
    borderRadius: 14,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "stretch",
  },
  statPill: {
    flex: 1,
    gap: 2,
    alignItems: "center",
    justifyContent: "center",
  },
  statLabel: {
    fontFamily: "Inter_500Medium",
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 0.45,
    color: colors.textMuted,
  },
  statValue: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 15,
    color: colors.textPrimary,
  },
  statDivider: {
    width: 1,
    alignSelf: "stretch",
    backgroundColor: colors.border,
  },
  clearText: {
    fontFamily: "Inter_500Medium",
    fontSize: 13,
    color: colors.error,
  },
  clearTextDisabled: {
    color: colors.textMuted,
  },
  clearAction: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  emptySelectionRow: {
    marginTop: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: colors.border,
    backgroundColor: colors.background,
    paddingVertical: 13,
    alignItems: "center",
    justifyContent: "center",
  },
  emptySelectionText: {
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    color: colors.textMuted,
  },
  cornerComposeButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    borderRadius: 14,
    paddingLeft: 10,
    paddingRight: 7,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: "#B56A0E",
    backgroundColor: colors.secondary,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 2,
    transform: [{ rotate: "-2deg" }],
  },
  cornerComposeButtonDisabled: {
    backgroundColor: colors.backgroundDark,
    borderColor: colors.border,
    shadowOpacity: 0,
    elevation: 0,
    transform: [{ rotate: "0deg" }],
  },
  cornerComposeLabel: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    letterSpacing: 0.2,
  },
  cornerComposeIconWrap: {
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.white,
  },
  cornerComposeIconWrapDisabled: {
    backgroundColor: colors.background,
  },
  selectedListRow: {
    paddingTop: 12,
    gap: 10,
  },
  selectedThumbWrap: {
    width: 62,
    height: 62,
    borderRadius: 14,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.backgroundSecondary,
  },
  selectedThumbImage: {
    width: "100%",
    height: "100%",
  },
  selectedThumbClose: {
    position: "absolute",
    top: 5,
    right: 5,
    width: 16,
    height: 16,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#1E1813B3",
  },
  sectionRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    marginTop: 2,
  },
  sectionTitle: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 15,
    color: colors.textPrimary,
  },
  sectionHint: {
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    color: colors.textMuted,
  },
  filterRow: {
    gap: 8,
    paddingVertical: 2,
    paddingHorizontal: 1,
  },
  filterPill: {
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderWidth: 1,
  },
  filterPillActive: {
    backgroundColor: colors.secondary,
    borderColor: colors.secondary,
  },
  filterPillIdle: {
    backgroundColor: colors.cardBg,
    borderColor: colors.border,
  },
  filterPillText: {
    fontFamily: "Inter_500Medium",
    fontSize: 13,
  },
  gridWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  gridCard: {
    borderRadius: 18,
    overflow: "hidden",
    backgroundColor: colors.cardBg,
    borderWidth: 1,
  },
  gridImage: {
    width: "100%",
    height: "100%",
  },
  gridMetaOverlay: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 10,
    paddingVertical: 9,
    backgroundColor: "#FCF9F5E6",
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  gridItemTitle: {
    fontFamily: "Inter_500Medium",
    fontSize: 12,
    color: colors.textSecondary,
  },
  gridSelectedChip: {
    position: "absolute",
    top: 9,
    right: 9,
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 5,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 4,
    backgroundColor: colors.secondary,
  },
  gridSelectedText: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 10,
    color: colors.white,
    letterSpacing: 0.2,
  },
  emptyCategoryState: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.cardBg,
    paddingVertical: 30,
    marginTop: 2,
  },
  emptyCategoryText: {
    marginTop: 10,
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    color: colors.textMuted,
  },
});
