import { StyleSheet } from "react-native";

const PREVIEW_THUMB_SIZE = 56;

export const s = StyleSheet.create({
  headerTitle: {
    fontFamily: "PlayfairDisplay_600SemiBold",
    fontSize: 20,
    color: "#3D2E22",
    letterSpacing: -0.3,
  },
  continueText: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 14,
  },
  previewCard: {
    borderRadius: 16,
    padding: 16,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#F0E8DC",
    shadowColor: "#C9BAAA",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
  },
  previewTransitionContainer: {
    overflow: "hidden",
  },
  previewAnimatedSlot: {
    overflow: "hidden",
  },
  previewHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  previewTitle: {
    fontFamily: "PlayfairDisplay_500Medium",
    fontSize: 15,
    color: "#3D2E22",
  },
  previewCount: {
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    color: "#9B8B7F",
    marginLeft: 8,
  },
  clearText: {
    fontFamily: "Inter_500Medium",
    fontSize: 12,
    color: "#D25037",
  },
  emptyPreview: {
    borderRadius: 12,
    paddingVertical: 24,
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "#E8DED3",
    backgroundColor: "#F5EFE6",
  },
  emptyPreviewContent: {
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  createMascot: {
    width: 132,
    height: 132,
    opacity: 0.95,
  },
  emptyPreviewText: {
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    color: "#9B8B7F",
    textAlign: "center",
  },
  thumbWrap: {
    width: PREVIEW_THUMB_SIZE,
    height: PREVIEW_THUMB_SIZE,
    borderRadius: 12,
    overflow: "hidden",
    backgroundColor: "#F5EFE6",
    borderWidth: 1,
    borderColor: "#D4A57460",
  },
  thumbClose: {
    position: "absolute",
    top: 2,
    right: 2,
    height: 16,
    width: 16,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#9B8B7FCC",
  },
  categoryBar: {
    paddingBottom: 12,
    paddingTop: 8,
    backgroundColor: "#FAF7F2",
    borderBottomWidth: 1,
    borderBottomColor: "#F0E8DC",
  },
  categoryWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    paddingHorizontal: 16,
  },
  pill: {
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderWidth: 1,
  },
  pillActive: {
    backgroundColor: "#D4A574",
    borderColor: "#D4A574",
  },
  pillInactive: {
    backgroundColor: "#FFFFFF",
    borderColor: "#F0E8DC",
  },
  pillText: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 13,
  },
  pillToggle: {
    backgroundColor: "#F5EFE6",
    borderColor: "#E8DED3",
    flexDirection: "row",
    alignItems: "center",
  },
  pillToggleText: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 13,
    color: "#6B5B4F",
    marginRight: 4,
  },
  gridCard: {
    borderRadius: 16,
    overflow: "hidden",
    backgroundColor: "#FFFFFF",
  },
  checkBadge: {
    position: "absolute",
    top: 6,
    right: 6,
    height: 24,
    width: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#D4A574",
  },
  gridLabel: {
    fontFamily: "Inter_500Medium",
    fontSize: 11,
    color: "#6B5B4F",
    textAlign: "center",
    marginTop: 4,
  },
  loadingText: {
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    color: "#9B8B7F",
    marginTop: 16,
  },
  errorMascot: {
    width: 120,
    height: 120,
    marginBottom: 20,
    opacity: 0.6,
  },
  errorHint: {
    fontFamily: "Inter_500Medium",
    fontSize: 13,
    color: "#9B8B7F",
    textAlign: "center",
    marginTop: 4,
  },
  emptyIcon: {
    height: 96,
    width: 96,
    borderRadius: 48,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
    backgroundColor: "#F7E9D7",
  },
  emptyTitle: {
    fontFamily: "PlayfairDisplay_600SemiBold",
    fontSize: 18,
    color: "#6B5B4F",
    marginBottom: 8,
    textAlign: "center",
  },
  emptySubtitle: {
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    color: "#9B8B7F",
    textAlign: "center",
  },
  buttonText: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 14,
    color: "#FFFFFF",
  },
});
