import { Dimensions, StyleSheet } from "react-native";

const screenWidth = Dimensions.get("window").width;
const CARD_WIDTH = (screenWidth - 48) / 2;

export const styles = StyleSheet.create({
  headerTitle: {
    fontFamily: "PlayfairDisplay_600SemiBold",
    fontSize: 22,
    color: "#3D2E22",
    letterSpacing: -0.3,
  },
  refreshButton: {
    height: 40,
    width: 40,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 20,
    backgroundColor: "#D4A57415",
  },
  sectionTitle: {
    fontFamily: "PlayfairDisplay_600SemiBold",
    fontSize: 18,
    color: "#3D2E22",
    letterSpacing: -0.2,
  },
  sectionSubtitle: {
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    color: "#9B8B7F",
  },
  outfitCard: {
    width: CARD_WIDTH,
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#F0E8DC",
    justifyContent: "space-between" as const,
    shadowColor: "#C9BAAA",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  outfitCardContent: {
    flex: 1,
  },
  outfitHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 10,
  },
  outfitLabel: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 13,
    color: "#3D2E22",
  },
  outfitGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  outfitItemThumb: {
    width: (CARD_WIDTH - 30) / 2,
    height: (CARD_WIDTH - 30) / 2,
    borderRadius: 10,
    overflow: "hidden",
    backgroundColor: "#FAF7F2",
    borderWidth: 1,
    borderColor: "#F0E8DC",
  },
  captureHost: {
    position: "absolute",
    left: -9999,
    top: -9999,
    opacity: 0,
    width: 220,
    height: 220,
  },
  captureCanvas: {
    width: 220,
    height: 220,
    backgroundColor: "#FAF7F2",
    borderRadius: 16,
    padding: 10,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  captureCell: {
    width: 96,
    height: 96,
    borderRadius: 10,
    overflow: "hidden",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#F0E8DC",
  },
  captureImage: {
    width: "100%",
    height: "100%",
  },
  captureCountBadge: {
    position: "absolute",
    right: 12,
    bottom: 12,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: "rgba(61, 46, 34, 0.85)",
  },
  captureCountBadgeText: {
    color: "#FFFFFF",
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    lineHeight: 14,
  },
  thumbPlaceholder: {
    fontFamily: "PlayfairDisplay_600SemiBold",
    fontSize: 16,
    color: "#9B8B7F",
  },
  moreItems: {
    fontFamily: "Inter_400Regular",
    fontSize: 11,
    color: "#9B8B7F",
    textAlign: "center",
    marginTop: 4,
  },
  mascot: {
    width: 160,
    height: 160,
    marginBottom: 24,
  },
  emptyTitle: {
    fontFamily: "PlayfairDisplay_600SemiBold",
    fontSize: 20,
    color: "#3D2E22",
    marginBottom: 8,
    textAlign: "center",
  },
  emptySubtitle: {
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    color: "#9B8B7F",
    textAlign: "center",
    lineHeight: 20,
    maxWidth: 280,
  },
  categoryHint: {
    fontFamily: "Inter_500Medium",
    fontSize: 13,
    color: "#B89E8E",
    textAlign: "center",
    marginTop: 12,
    lineHeight: 18,
    maxWidth: 260,
  },
  progressRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 24,
    marginBottom: 8,
  },
  progressDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
  },
  progressDotFilled: {
    backgroundColor: "#D4A574",
  },
  progressDotEmpty: {
    backgroundColor: "#F0E8DC",
  },
  progressText: {
    fontFamily: "Inter_500Medium",
    fontSize: 13,
    color: "#9B8B7F",
  },
  loadingText: {
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    color: "#9B8B7F",
    marginTop: 16,
  },
  emptyIcon: {
    height: 96,
    width: 96,
    borderRadius: 48,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
    backgroundColor: "#F7E9D7",
  },
  errorMascot: {
    width: 120,
    height: 120,
    marginBottom: 20,
    opacity: 0.6,
  },
  retryText: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 14,
    color: "#FFFFFF",
  },
  saveButton: {
    marginTop: 10,
    backgroundColor: "#D4A574",
    borderRadius: 10,
    paddingVertical: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  saveButtonSaved: {
    backgroundColor: "#8BAF7A",
  },
  saveButtonText: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: "#FFFFFF",
  },
});
