import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  flex: {
    flex: 1,
  },
  headerTitle: {
    fontFamily: "PlayfairDisplay_600SemiBold",
    fontSize: 20,
    color: "#3D2E22",
    letterSpacing: -0.3,
  },
  heroSection: {
    alignItems: "center",
    paddingTop: 24,
    paddingBottom: 8,
    paddingHorizontal: 24,
  },
  avatar: {
    width: 100,
    height: 100,
    borderRadius: 50,
    shadowColor: "#D4A574",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 4,
  },
  avatarFallback: {
    fontFamily: "PlayfairDisplay_600SemiBold",
    fontSize: 32,
  },
  name: {
    fontFamily: "PlayfairDisplay_600SemiBold",
    fontSize: 26,
    marginTop: 16,
    color: "#3D2E22",
    letterSpacing: -0.3,
  },
  email: {
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    marginTop: 4,
    color: "#9B8B7F",
  },
  divider: {
    height: 1,
    width: 40,
    marginTop: 24,
  },
  statsCard: {
    flexDirection: "row",
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    marginHorizontal: 24,
    marginTop: 24,
    paddingVertical: 20,
    borderWidth: 1,
    borderColor: "#F0E8DC",
    shadowColor: "#C9BAAA",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
  },
  statItem: {
    flex: 1,
    alignItems: "center",
  },
  statNumber: {
    fontFamily: "PlayfairDisplay_600SemiBold",
    fontSize: 20,
    color: "#3D2E22",
  },
  statLabel: {
    fontFamily: "Inter_400Regular",
    fontSize: 11.5,
    marginTop: 4,
    color: "#9B8B7F",
    letterSpacing: 0.2,
  },
  statDivider: {
    width: 1,
    height: 32,
    alignSelf: "center",
  },
  sectionHeader: {
    paddingHorizontal: 24,
    marginTop: 32,
    marginBottom: 12,
  },
  sectionLabel: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    letterSpacing: 1.5,
    color: "#9B8B7F",
  },
  settingsCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    marginHorizontal: 24,
    borderWidth: 1,
    borderColor: "#F0E8DC",
    shadowColor: "#C9BAAA",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
  },
  settingsItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 14,
    paddingHorizontal: 16,
  },
  settingsItemLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  iconCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  settingsLabel: {
    fontFamily: "Inter_500Medium",
    fontSize: 15,
    color: "#3D2E22",
  },
  settingsDivider: {
    height: 1,
    marginLeft: 64,
  },
  signOut: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 32,
    paddingVertical: 8,
  },
  signOutText: {
    fontFamily: "Inter_500Medium",
    fontSize: 14,
    marginLeft: 8,
    color: "#D25037",
  },
  footer: {
    fontFamily: "PlayfairDisplay_400Regular",
    fontSize: 12,
    textAlign: "center",
    marginTop: 24,
    marginBottom: 40,
    color: "#9B8B7F",
    opacity: 0.6,
    letterSpacing: 0.3,
  },
});
