import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  closeButton: {
    height: 40,
    width: 40,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 20,
    backgroundColor: "#8B735512",
  },
  headerTitle: {
    fontFamily: "PlayfairDisplay_600SemiBold",
    fontSize: 18,
    color: "#3D2E22",
    letterSpacing: -0.3,
  },
  nextButton: {
    height: 40,
    paddingHorizontal: 16,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 20,
  },
  nextText: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 14,
  },
  selectPhotoText: {
    fontFamily: "Inter_400Regular",
    fontSize: 15,
    color: "#9B8B7F",
    marginTop: 12,
  },
  galleryHeader: {
    height: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    backgroundColor: "#FAF7F2",
    borderTopWidth: 1,
    borderTopColor: "#F0E8DC",
    borderBottomWidth: 1,
    borderBottomColor: "#F0E8DC",
  },
  galleryLabel: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 13,
    color: "#3D2E22",
    marginRight: 4,
  },
  photoCount: {
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    color: "#9B8B7F",
  },
  cameraLabel: {
    fontFamily: "Inter_500Medium",
    fontSize: 12,
    color: "#6B5B4F",
    marginTop: 8,
  },
  albumSheet: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "#F0E4D6",
    backgroundColor: "#FFFDFC",
    overflow: "hidden",
  },
  sheetHandle: {
    alignSelf: "center",
    width: 42,
    height: 5,
    borderRadius: 999,
    backgroundColor: "#E2D5C6",
    marginTop: 10,
  },
  sheetHeader: {
    paddingTop: 10,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#F3E9DE",
  },
  sheetTitle: {
    fontFamily: "PlayfairDisplay_600SemiBold",
    fontSize: 18,
    color: "#3D2E22",
    letterSpacing: -0.2,
  },
  sheetSubtitle: {
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    color: "#9B8B7F",
    marginTop: 2,
  },
  sheetCloseButton: {
    height: 34,
    width: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#8B735512",
  },
  albumRow: {
    minHeight: 52,
    borderRadius: 14,
    paddingHorizontal: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#F0E8DC",
    backgroundColor: "#FFFFFF",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  albumRowActive: {
    borderColor: "#E7C79F",
    backgroundColor: "#FFF6E8",
  },
  albumRowLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    paddingRight: 10,
  },
  albumRowIcon: {
    height: 28,
    width: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
    backgroundColor: "#F8EEDD",
  },
  albumTitle: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 14,
    color: "#3D2E22",
  },
  albumTitleActive: {
    color: "#B57A39",
  },
  albumSubtitle: {
    fontFamily: "Inter_400Regular",
    fontSize: 11,
    color: "#9B8B7F",
    marginTop: 1,
  },
});
