import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  headerTitle: {
    fontFamily: "PlayfairDisplay_600SemiBold",
    fontSize: 22,
    color: "#3D2E22",
    letterSpacing: -0.3,
  },
  tabContainer: {
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  tabBar: {
    flexDirection: "row",
    borderRadius: 999,
    padding: 4,
    backgroundColor: "#F5EFE6",
  },
  tab: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 999,
    alignItems: "center",
  },
  tabActive: {
    backgroundColor: "#FFFFFF",
    shadowColor: "#C9BAAA",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 1,
  },
  tabText: {
    fontFamily: "Inter_500Medium",
    fontSize: 14,
    color: "#9B8B7F",
  },
  tabTextActive: {
    fontFamily: "Inter_600SemiBold",
    color: "#3D2E22",
  },
  weatherCard: {
    marginHorizontal: 16,
    marginTop: 8,
    marginBottom: 2,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E9DFD1",
    backgroundColor: "#FBF7F0",
  },
  weatherCity: {
    fontFamily: "PlayfairDisplay_600SemiBold",
    fontSize: 16,
    color: "#3D2E22",
  },
  weatherLine: {
    fontFamily: "Inter_500Medium",
    fontSize: 14,
    color: "#6B5B4F",
    marginTop: 4,
  },
  weatherHint: {
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    color: "#9B8B7F",
    marginTop: 6,
  },
  categoryCircle: {
    height: 56,
    width: 56,
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
    backgroundColor: "#F5EFE6",
  },
  categoryCircleActive: {
    backgroundColor: "#F7E9D7",
    borderWidth: 2,
    borderColor: "#D4A574",
  },
  categoryLabel: {
    fontFamily: "Inter_400Regular",
    fontSize: 11,
    color: "#9B8B7F",
  },
  categoryLabelActive: {
    fontFamily: "Inter_600SemiBold",
    color: "#D4A574",
  },
  categoryLetter: {
    fontFamily: "PlayfairDisplay_600SemiBold",
    fontSize: 20,
  },
  itemCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#F0E8DC",
    shadowColor: "#C9BAAA",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  itemLabel: {
    position: "absolute",
    left: 8,
    right: 8,
    bottom: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: "rgba(255, 255, 255, 0.92)",
    borderRadius: 8,
  },
  itemLabelText: {
    fontFamily: "Inter_500Medium",
    fontSize: 12,
    color: "#3D2E22",
    textAlign: "center",
  },
  loadingText: {
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    color: "#9B8B7F",
    marginTop: 16,
  },
  emptyIcon: {
    height: 96,
    width: 96,
    borderRadius: 48,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
    backgroundColor: "#F7E9D7",
  },
  emptyTitle: {
    fontFamily: "PlayfairDisplay_600SemiBold",
    fontSize: 18,
    color: "#6B5B4F",
    marginBottom: 8,
    textAlign: "center",
  },
  emptySubtitle: {
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    color: "#9B8B7F",
    textAlign: "center",
  },
  modalTitle: {
    fontFamily: "PlayfairDisplay_600SemiBold",
    fontSize: 18,
    color: "#3D2E22",
    letterSpacing: -0.2,
  },
  modalImageCard: {
    height: 220,
    borderRadius: 12,
    overflow: "hidden",
    backgroundColor: "#FAF7F2",
    borderWidth: 1,
    borderColor: "#F0E8DC",
  },
  modalItemTitle: {
    fontFamily: "PlayfairDisplay_600SemiBold",
    fontSize: 20,
    color: "#3D2E22",
    letterSpacing: -0.3,
  },
  modalItemSub: {
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    color: "#9B8B7F",
  },
  modalDescription: {
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    color: "#6B5B4F",
    lineHeight: 20,
  },
  modalSectionLabel: {
    fontFamily: "Inter_500Medium",
    fontSize: 13,
    color: "#9B8B7F",
  },
  modalDate: {
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    color: "#9B8B7F",
  },
  alertTitle: {
    fontFamily: "PlayfairDisplay_600SemiBold",
    fontSize: 17,
    color: "#3D2E22",
  },
  alertBody: {
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    color: "#6B5B4F",
    lineHeight: 20,
  },
  errorMascot: {
    width: 120,
    height: 120,
    marginBottom: 20,
    opacity: 0.6,
  },
  errorHint: {
    fontFamily: "Inter_500Medium",
    fontSize: 13,
    color: "#9B8B7F",
    textAlign: "center",
    marginTop: 4,
  },
  retryText: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 14,
    color: "#FFFFFF",
  },
});
