import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    flex: {
        flex: 1,
    },
    backButton: {
        height: 40,
        width: 40,
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 20,
        backgroundColor: "#8B735512",
        marginRight: 8,
    },
    headerTitle: {
        fontFamily: "PlayfairDisplay_600SemiBold",
        fontSize: 20,
        color: "#3D2E22",
        letterSpacing: -0.3,
    },
    identitySection: {
        alignItems: "center",
        paddingTop: 32,
        paddingBottom: 8,
    },
    mascot: {
        width: 80,
        height: 80,
        borderRadius: 24,
        marginBottom: 16,
    },
    appName: {
        fontFamily: "PlayfairDisplay_600SemiBold",
        fontSize: 26,
        color: "#3D2E22",
        letterSpacing: -0.3,
    },
    version: {
        fontFamily: "Inter_400Regular",
        fontSize: 13,
        color: "#9B8B7F",
        marginTop: 4,
    },
    descriptionWrap: {
        paddingHorizontal: 32,
        paddingBottom: 8,
        paddingTop: 8,
    },
    description: {
        fontFamily: "Inter_400Regular",
        fontSize: 14,
        textAlign: "center",
        lineHeight: 21,
        color: "#6B5B4F",
    },
    card: {
        marginHorizontal: 20,
        marginTop: 20,
        backgroundColor: "#FFFFFF",
        borderRadius: 16,
        borderWidth: 1,
        borderColor: "#F0E8DC",
        shadowColor: "#C9BAAA",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 10,
        elevation: 2,
        overflow: "hidden",
    },
    cardHeader: {
        fontFamily: "PlayfairDisplay_500Medium",
        fontSize: 13,
        color: "#9B8B7F",
        letterSpacing: 0.3,
        paddingHorizontal: 16,
        paddingTop: 16,
        paddingBottom: 4,
    },
    cardBody: {
        paddingHorizontal: 16,
        paddingBottom: 4,
    },
    featureRow: {
        flexDirection: "row",
        alignItems: "flex-start",
        paddingVertical: 12,
    },
    featureIcon: {
        height: 32,
        width: 32,
        borderRadius: 16,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#D4A57415",
        marginRight: 12,
        marginTop: 2,
    },
    featureContent: {
        flex: 1,
    },
    featureTitle: {
        fontFamily: "Inter_600SemiBold",
        fontSize: 14,
        color: "#3D2E22",
    },
    featureDesc: {
        fontFamily: "Inter_400Regular",
        fontSize: 12.5,
        color: "#6B5B4F",
        marginTop: 2,
        lineHeight: 18,
    },
    featureDivider: {
        height: 1,
        backgroundColor: "#F0E8DC",
        marginLeft: 44,
    },
    techRow: {
        flexDirection: "row",
        alignItems: "center",
        paddingVertical: 14,
    },
    techIcon: {
        height: 32,
        width: 32,
        borderRadius: 16,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#D4A57415",
        marginRight: 12,
    },
    techContent: {
        flex: 1,
    },
    techTitle: {
        fontFamily: "Inter_500Medium",
        fontSize: 14,
        color: "#3D2E22",
    },
    techSub: {
        fontFamily: "Inter_400Regular",
        fontSize: 12,
        color: "#9B8B7F",
        marginTop: 2,
    },
    footer: {
        alignItems: "center",
        paddingVertical: 32,
        paddingBottom: 40,
    },
    footerRow: {
        flexDirection: "row",
        alignItems: "center",
    },
    footerText: {
        fontFamily: "Inter_400Regular",
        fontSize: 12,
        color: "#9B8B7F",
    },
    copyright: {
        fontFamily: "PlayfairDisplay_400Regular",
        fontSize: 12,
        color: "#9B8B7F",
        marginTop: 8,
        opacity: 0.6,
        letterSpacing: 0.3,
    },
});
