import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    flex: {
        flex: 1,
    },
    backButton: {
        height: 40,
        width: 40,
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 20,
        backgroundColor: "#8B735512",
        marginRight: 8,
    },
    headerTitle: {
        fontFamily: "PlayfairDisplay_600SemiBold",
        fontSize: 20,
        color: "#3D2E22",
        letterSpacing: -0.3,
    },
    card: {
        marginHorizontal: 20,
        marginTop: 20,
        backgroundColor: "#FFFFFF",
        borderRadius: 16,
        borderWidth: 1,
        borderColor: "#F0E8DC",
        shadowColor: "#C9BAAA",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 10,
        elevation: 2,
        overflow: "hidden",
    },
    cardHeader: {
        fontFamily: "PlayfairDisplay_500Medium",
        fontSize: 13,
        color: "#9B8B7F",
        letterSpacing: 0.3,
        paddingHorizontal: 16,
        paddingTop: 16,
        paddingBottom: 4,
    },
    cardBody: {
        paddingHorizontal: 16,
    },
    faqRow: {
        flexDirection: "row",
        alignItems: "center",
        paddingVertical: 14,
    },
    faqIcon: {
        height: 32,
        width: 32,
        borderRadius: 16,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#D4A57415",
        marginRight: 12,
    },
    faqQuestion: {
        fontFamily: "Inter_500Medium",
        fontSize: 14,
        color: "#3D2E22",
        flex: 1,
    },
    faqAnswer: {
        marginLeft: 44,
        marginBottom: 14,
        padding: 12,
        borderRadius: 12,
        backgroundColor: "#FAF7F2",
    },
    faqAnswerText: {
        fontFamily: "Inter_400Regular",
        fontSize: 13.5,
        lineHeight: 20,
        color: "#6B5B4F",
    },
    faqDivider: {
        height: 1,
        backgroundColor: "#F0E8DC",
        marginLeft: 44,
    },
    contactRow: {
        flexDirection: "row",
        alignItems: "center",
        paddingVertical: 14,
    },
    contactIcon: {
        height: 36,
        width: 36,
        borderRadius: 18,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#D4A57415",
        marginRight: 12,
    },
    contactContent: {
        flex: 1,
    },
    contactTitle: {
        fontFamily: "Inter_500Medium",
        fontSize: 14,
        color: "#3D2E22",
    },
    contactSub: {
        fontFamily: "Inter_400Regular",
        fontSize: 12,
        color: "#9B8B7F",
        marginTop: 2,
    },
});
